language: node_js

env:
  - SENECA_VER=senecajs/seneca

node_js:
  - '14'
  - '13'
  - '12'
  - '10'

before_script:
  - npm uninstall seneca
  - npm install $SENECA_VER

after_script:
  - npm run coveralls

os:
  - "linux"
  - "osx"
  - "windows"
